fieldLayouts:
  ac4d794b-1a8d-41bb-b520-b09eb09ae858:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Polly Edwards'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58cd9c5d-03d3-40dd-8581-f47b43436be6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28901fa8-0b6c-48af-a81f-030a2295d015 # Image 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a98476f-29a0-4370-9943-f335600b150c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58ac0044-d9cc-4267-bc73-a897c2f23f26 # image 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f86dabf-b4ec-486d-bdd7-eadfe136c6ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0b2a2f7-c3ac-4400-bf5d-ef0d30249aa7 # image3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dc5746b-ae3b-4a33-b953-dd278eb39513
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e103d5e-81c2-4a5c-b927-f577c73d2c65 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41fe3d18-ca96-44a8-9f94-2dfef25f3050
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: faff8b18-84ef-4767-a27d-3debd81f5dcf # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29ca9c73-43fb-4090-84f2-facb1fe3d056
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f083752-82c6-4c21-9c00-b77ab36ee8f8 # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03ef86ae-7e37-452e-a4b1-da13d46926e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1ac4818-cc4e-419d-87e8-bf73d1289f15
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: d2beb882-0ee5-4c50-925d-14cff94304fe # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
