baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Polly Edwards Music'
primary: true
siteGroup: c7075ff2-22ea-4848-a584-0ffe6d2ac419 # pollyedwardsmusic
sortOrder: 1
